apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: random-app
  labels:
    app: random-app
spec:
  replicas: 1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: random-app
    spec:
      containers:
      - name: random-app
        image: "gcr.io/cloudorbit/random-app:v3"
        env:
        - name: REDISHOST
          valueFrom:
            configMapKeyRef:
              name: redishost
              key: REDISHOST
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: random-app
spec:
  type: LoadBalancer
  selector:
    app: random-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
